---
- name: Upload {{ application_name }} to S3
  hosts: localhost
  connection: local
  remote_user: itops
  become: yes
  gather_facts: no  
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - upload_installer_to_s3